export const projects = [
  {
    name: "MDDV.com",
    type: "Website",
    section: ["Developer"],
    featured: true,
    description:
      "The company website for American Data Solutions (ADS) and its proprietary IETM software, MDDV.",
    tech: ["Next.js", "React", "Typescript", "Tailwind CSS"],
    link: "https://mddv.com/",
    icon: "xword-logo",
    colors: {
      key: "#08c",
      alt: "white",
      dark: "black",
      reverse: false,
    },
    images: [
      { src: "projects/mddv-1.png" },
      { src: "projects/mddv-2.png" },
      { src: "projects/mddv-3.png" },
      { src: "projects/mddv-4.png" },
    ],
  },
  {
    name: "XWord",
    type: "Game",
    isWip: false,
    section: ["Developer", "Game"],
    featured: true,
    repo: {
      platform: "Github",
      link: "https://github.com/jbrooks890/crossword",
    },
    description:
      "A crossword puzzle application built on an original grid-based architecture for creating and playing trivia-based puzzle games.",
    meta: {},
    tech: ["React", "Typescript", "MongoDB", "Node", "SASS"],
    link: "https://xword-app-beta.netlify.app/",
    icon: "xword-logo",
    colors: {
      key: "#5b42ff",
      alt: "#8840f2",
      alt2: "#51f23f",
      dark: "#150330",
      reverse: false,
    },
    images: [{ src: "projects/xword-4.png" }, { src: "projects/xword-5.png" }],
  },
  {
    name: "Worlds of EPOCH",
    type: "Website",
    isWip: false,
    section: ["Developer"],
    featured: true,
    repo: {
      platform: "",
      link: "",
    },
    description:
      "The official website of my independent publishing company EPOCH Studios.",
    meta: {},
    tech: ["Squarespace", "JavaScript", "HTML", "CSS"],
    link: "https://www.worldsofepoch.com/",
    icon: "epoch-logo",
    colors: {
      key: "#feee36",
      alt: "#6c9393",
      dark: "#161d1d",
      reverse: false,
    },
    images: [
      { src: "projects/epoch-site-1.png" },
      { src: "projects/epoch-site-2.png" },
    ],
  },
  {
    name: "PokéSquad",
    type: "Website",
    isWip: true,
    section: ["Developer"],
    featured: true,
    repo: {
      platform: "Github",
      link: "https://github.com/jbrooks890/Poke-Squad",
    },
    description:
      "A fun companion app that queries the _PokéAPI_, enabling users to simulate building their ideal teams for Nintendo's popular _Pokémon_ games.",
    meta: {},
    tech: ["React", "Postman"],
    link: "https://pokesquad.netlify.app/",
    icon: "pokesquad-logo",
    colors: {
      key: "#ff0000",
      alt: "#fff",
      dark: "",
      reverse: true,
    },
    images: [
      { src: "projects/pokesquad-1.png" },
      { src: "projects/pokesquad-2.png" },
    ],
  },
  {
    name: "Arcan",
    type: "Story",
    isWip: false,
    section: ["Writer", "Artist"],
    featured: true,
    repo: {
      platform: "",
      link: "",
    },
    description:
      "A Fantasy/Sci-Fi series following Kyran on his epic journey to stop the Exxarians from undoing all Created.",
    meta: {
      genre: ["Fantasy", "Sci-Fi"],
      imprint: "EXP",
    },
    tech: ["HTML", "CSS", "JavaScript", "Photoshop", "Illustrator", "InDesign"],
    link: "https://www.worldsofepoch.com/arcan",
    icon: "arcan-logo",
    colors: {
      key: "#00bfa7",
      alt: "",
      dark: "#000",
      reverse: false,
    },
    images: [{ src: "gallery/arcan__web-Banner.jpg" }],
  },
  {
    name: "The Dark Ones",
    type: "Story",
    isWip: true,
    section: ["Writer"],
    featured: false,
    repo: {
      platform: "",
      link: "",
    },
    description:
      "Enoch, the apprentice of a great Guardian Angel, is left to defend Calvin and the rest of his family when they come under attack by both fiends of the spiritual plane and greedy corporate moguls.",
    meta: {
      genre: ["Fantasy", "Sci-Fi"],
      imprint: "EXP",
      publisher: "EPOCH Studios",
    },
    tech: [],
    link: "",
    icon: "",
    colors: {
      key: "",
      alt: "",
      dark: "",
      reverse: false,
    },
    images: [],
  },
  {
    name: "Andromata",
    type: "Story",
    isWip: true,
    section: ["Writer"],
    featured: false,
    repo: {
      platform: "",
      link: "",
    },
    description:
      "In the very distant future, Earth has ventured into space and thusly earned its share of extraterrestrial adversaries. Dash and Aniko are selected as combat pilots for the UXG's new Armanaut program, debuting a new type of mech: Megaframes with Andromata as its flagship.",
    meta: {
      genre: ["Sci-Fi"],
      imprint: "EXP",
      publisher: "EPOCH Studios",
    },
    tech: [],
    link: "",
    icon: "",
    colors: {
      key: "",
      alt: "",
      dark: "",
      reverse: false,
    },
    images: [],
  },
  {
    name: "Crymsica",
    type: "Brand",
    isWip: false,
    section: ["Game"],
    featured: false,
    repo: {
      platform: "",
      link: "",
    },
    description:
      "Crymsica Games is the division of EPOCH Studios dedicated to the development of video games and other visual media.",
    meta: {},
    tech: [],
    link: "",
    icon: "crymsica-lion",
    colors: {
      key: "#d10000",
      alt: "",
      dark: "#00000",
      reverse: false,
    },
    images: [],
  },
  {
    name: "T2 Com-bat",
    type: "Brand",
    isWip: false,
    section: ["Artist"],
    featured: true,
    repo: {
      platform: "",
      link: "",
    },
    description:
      "The Com-bat mascot of the MC-130H Combat Talon II aircraft is a symbol of its decades-long legacy in the Air Force Special Operations Command. This redesign was an effort to modernize its aesthetic while still honoring its history.",
    meta: {
      client: "15th AMU, U.S. Air Force",
    },
    tech: ["Illustrator", "Photoshop"],
    link: "",
    icon: "",
    colors: {
      key: "",
      alt: "",
      dark: "",
      reverse: false,
    },
    images: [
      { src: "gallery/t2__web.jpg" },
      { src: "gallery/t2-patch__web.jpg" },
    ],
  },
  {
    name: `_War Love_\nby Jessica Lá\u00A0Rel`,
    type: "Album Cover",
    isWip: false,
    section: ["Artist"],
    featured: true,
    repo: {
      platform: "",
      link: "",
    },
    description:
      "The cover art for R&B/Soul artist Jessica Lá\u00A0Rel\u2019s debut album, _War\u00A0Love_.",
    meta: {
      client: "Jessica Anderson (aka Jessica Lá Rel)",
    },
    tech: ["Illustrator", "Photoshop"],
    link: "https://jessicalarel.com/music/",
    icon: "",
    colors: {
      key: "",
      alt: "",
      dark: "",
      reverse: false,
    },
    images: [{ src: "gallery/war-love__web.jpg" }],
  },
];
