export const resumeData = {
  firstName: "Julian",
  middleName: "Christian",
  lastName: "Brooks",
  birthday: {
    month: "August",
    day: 16,
    year: 1990,
  },
  gender: "male",
  ethnicity: "Black/African-American",
  address: {
    streetNumber: 2645,
    streetName: "Rosalyn Lane",
    streetOther: "",
    streetOtherType: "",
    city: "Smyrna",
    state: "Georgia",
    zipCode: "30080-1811",
  },
  email: {
    primary: "jbrooks890@gmail.com",
    secondary: "jbrooks@worldsofepoch.com",
    other: ["jbrooks890@icloud.com"],
  },
  phone: {
    cell: 7738966276,
    home: 0,
    work: 0,
  },
  summary:
    "A creative problem solver with an entrepreneurial drive to deliver effective solutions and learn leading-edge technologies.",
  socialMedia: [
    {
      name: "GitHub",
      link: "https://github.com/jbrooks890",
      handle: "jbrooks890",
      icon: "github-logo",
    },
    {
      name: "LinkedIn",
      link: "https://www.linkedin.com/in/julian-c-brooks/",
      handle: "julian-c-brooks",
      icon: "linkedin-logo",
    },
    {
      name: "Instagram",
      link: "https://www.instagram.com/julian_wrote_this/",
      handle: "julian_wrote_this",
      icon: "ig-logo",
    },
    {
      name: "Facebook",
      link: "https://www.facebook.com/julianWroteThis/",
      handle: "julianWroteThis",
      icon: "fb-logo",
    },
    {
      name: "Twitter",
      link: "https://twitter.com/julianWroteThis",
      handle: "julianWroteThis",
      icon: "twitter-logo",
    },
  ],
  projects: [
    {
      name: "Pokésquad App",
      description:
        "A React application that allows the user to build, customize and save his team of Pokémon.",
      link: "https://pokesquad.netlify.app/",
      technologies: ["React", "Javascript", "HTML", "CSS"],
    },
    {
      name: "XWord App",
      description:
        "An application for creating and playing trivia-based crossword puzzle games.",
      link: "https://www.worldsofepoch.com/puzzle-demo/space",
      technologies: ["React", "Javascript", "HTML", "CSS"],
    },
    {
      name: "Web Reader App",
      description: "An application for reading text and markdown files.",
      link: "https://www.worldsofepoch.com/anthology/the-boy-who-dreamed",
      technologies: ["Javascript", "HTML", "CSS"],
    },
  ],
  experience: [
    {
      type: "personal",
      company: {
        name: "EPOCH Studios",
        address: {
          streetNumber: 2645,
          streetName: "Rosalyn Lane",
          streetOther: "",
          streetOtherType: "",
          city: "Smyrna",
          state: "Georgia",
          stateInitials: "GA",
          zipCode: "30080-1811",
        },
      },
      current: true,
      startDate: {
        month: "March",
        day: 1,
        year: 2016,
      },
      endDate: {
        month: "",
        day: 1,
        year: 2020,
      },
      roles: [
        {
          name: "Chief Editor",
          description:
            "Designed and created company to express the creative ideas of myself and other artists and authors.",
          tasks: [
            "Authored and published Arcan: The Missing Nexus novel",
            "Designed and developed company website (wireframe, layout, structure) for various platforms (desktop, mobile, tablet)",
            "Designed company brands and sub-brands, logos, wordmarks, icons, color palette, and other graphics",
            "Manage merchandise/product inventory, Product development and marketing",
            "Order fulfillment; packaging and shipping",
            "Proofreading, editing (copyediting, line editing) prior to publication]",
          ],
          skills: ["Proofreading", "copyediting", "branding"],
        },
      ],
    },
    {
      type: "professional",
      company: {
        name: "Epiq",
        address: {
          streetNumber: 2,
          streetName: "Ravinia Drive",
          streetOther: "",
          streetOtherType: "Suite",
          city: "Atlanta",
          state: "Georgia",
          stateInitials: "GA",
          zipCode: "30346-2104",
        },
      },
      current: false,
      startDate: {
        month: "October",
        day: 22,
        year: 2018,
      },
      endDate: {
        month: "March",
        day: 19,
        year: 2021,
      },
      roles: [
        {
          name: "Workflow Coordinator",
          description:
            "Management of workflow and delegation of work requests in a high-volume, fast-paced environment",
          tasks: [
            "Corresponded with clients to assess requirements and establish deadlines for work requests",
            "Managed queue of work request tickets, prioritizing and delegating tasks to operators",
          ],
          skills: ["time management"],
        },
        {
          name: "Document Specialist",
          description:
            "Prepared and converted official documentation for legal firms/law offices.",
          tasks: [
            "Converted various poor-quality/resolution documents (scans, sketches, etc.) into editable, dynamic documents utilizing various Microsoft Office tools and plugins",
            "Peer reviewed work request documents for quality assurance prior to delivery to the client",
            "Troubleshooted errors with “broken” documents, providing client with instructions remotely",
            "Maintained document organization and versioning via iManage document management system",
          ],
          skills: ["quality assurance"],
        },
      ],
    },
  ],
  education: [
    {
      type: "degree",
      institution: {
        name: "Kennesaw State University",
        address: {
          streetNumber: 1000,
          streetName: "Chastain Rd NW",
          streetOther: "",
          streetOtherType: "",
          city: "Kennesaw",
          state: "Georgia",
          stateInitials: "GA",
          zipCode: "30144-5591",
        },
        contact: {
          phone: 4705786000,
          email: "",
        },
      },
      current: true,
      startDate: {
        month: "June",
        day: 1,
        year: 2022,
      },
      endDate: {
        month: "",
        day: 1,
        year: 2022,
      },
      majors: [
        {
          name: "Computer Game Design & Development",
          degreeLevel: "undergraduate",
          degreeType: "Bachelor of Science",
          field: "Computer Science",
          tags: ["game design", "game development", "computer science", "tech"],
        },
      ],
      minors: [],
      other: [],
      notes: [
        "Transferred to school that provides more technical/development courses",
      ],
    },
    {
      type: "bootcamp",
      institution: {
        name: "Per Scholas",
        address: {
          streetNumber: 0,
          streetName: "",
          streetOther: "",
          streetOtherType: "",
          city: "Atlanta",
          state: "Georgia",
          stateInitials: "",
          zipCode: "",
        },
        contact: {
          phone: 0,
          email: "",
        },
      },
      current: false,
      startDate: {
        month: "May",
        day: 23,
        year: 2022,
      },
      endDate: {
        month: "September",
        day: 2,
        year: 2022,
      },
      majors: [],
      minors: [],
      other: [
        {
          name: "Software Engineering Bootcamp",
          conferralType: "certificate",
          field: "Software Engineering",
          tags: ["computer science", "tech", "web development"],
        },
      ],
      notes: [
        "Acquired hand-on experience with MERN full stack development, demonstrating high proficiencies in JavaScript, React, Node.js, and practical experience in database technologies including MongoDB and MySQL",
        "Bridged the gap in understanding of end-to-end development process and solidified abilities to deploy full stack applications in an agile team environment",
      ],
    },
  ],
  skills: [
    { name: "HTML", category: ["developer"], type: "language", primary: true },
    { name: "CSS", category: ["developer"], type: "language", primary: true },
    {
      name: "Javascript",
      category: ["developer"],
      type: "language",
      primary: true,
    },
    {
      name: "Node.js",
      category: ["developer"],
      type: "language",
      primary: true,
    },
    {
      name: "Express.js",
      category: ["developer"],
      type: "language",
      primary: true,
    },
    { name: "React", category: ["developer"], type: "language", primary: true },
    { name: "C#", category: ["developer"], type: "language", primary: false },
    {
      name: "MongoDB",
      category: ["developer"],
      type: "language",
      primary: true,
    },
    {
      name: "NoSQL",
      category: ["developer"],
      type: "language",
      primary: false,
    },
    { name: "MySQL", category: ["developer"], type: "language", primary: true },
    { name: "SQL", category: ["developer"], type: "language", primary: false },
    {
      name: "MongoDB Compass",
      category: ["developer"],
      type: "tool",
      primary: false,
    },
    {
      name: "MongoDB Atlas",
      category: ["developer"],
      type: "tool",
      primary: false,
    },
    {
      name: "Mongoose",
      category: ["developer"],
      type: "language",
      primary: false,
    },
    {
      name: "Mongo Shell",
      category: ["developer"],
      type: "tool",
      primary: false,
    },
    {
      name: "MySQL Workbench",
      category: ["developer"],
      type: "tool",
      primary: false,
    },
    { name: "Postman", category: ["developer"], type: "tool", primary: true },
    { name: "Git", category: ["developer"], type: "tool", primary: true },
    { name: "GitHub", category: ["developer"], type: "tool", primary: true },
    {
      name: "Squarespace",
      category: ["developer"],
      type: "tool",
      primary: true,
    },
    {
      name: "Adobe Photoshop",
      category: ["artist"],
      type: "tool",
      primary: false,
    },
    {
      name: "Adobe Illustrator",
      category: ["artist"],
      type: "tool",
      primary: false,
    },
    {
      name: "Adobe InDesign",
      category: ["artist"],
      type: "tool",
      primary: false,
    },
    {
      name: "Adobe Acrobat",
      category: ["general"],
      type: "tool",
      primary: false,
    },
    {
      name: "Adobe Bridge",
      category: ["artist"],
      type: "tool",
      primary: false,
    },
    { name: "Adobe XD", category: ["artist"], type: "tool", primary: false },
    {
      name: "Figma",
      category: ["developer", "artist"],
      type: "tool",
      primary: false,
    },
    {
      name: "Microsoft Word",
      category: ["general"],
      type: "tool",
      primary: false,
    },
    {
      name: "Microsoft Excel",
      category: ["general"],
      type: "tool",
      primary: false,
    },
    { name: "PowerPoint", category: ["general"], type: "tool", primary: false },
    {
      name: "Microsoft Outlook",
      category: ["general"],
      type: "tool",
      primary: false,
    },
    {
      name: "Microsoft Teams",
      category: ["general"],
      type: "tool",
      primary: false,
    },
    {
      name: "Visual Studio Code",
      category: ["developer"],
      type: "tool",
      primary: false,
    },
    {
      name: "Autodesk Maya",
      category: ["artist"],
      type: "tool",
      primary: false,
    },
    { name: "ZBrush", category: ["artist"], type: "tool", primary: false },
    {
      name: "Adobe Substance Painter",
      category: ["artist"],
      type: "",
      primary: false,
    },
    {
      name: "MERN",
      category: ["developer"],
      type: "proficiency",
      primary: false,
    },
    {
      name: "Version Control",
      category: ["developer"],
      type: "proficiency",
      primary: false,
    },
    {
      name: "REST",
      category: ["developer"],
      type: "proficiency",
      primary: false,
    },
    {
      name: "RESTful",
      category: ["developer"],
      type: "proficiency",
      primary: false,
    },
    {
      name: "API Design/Development",
      category: ["developer"],
      type: "proficiency",
      primary: false,
    },
    {
      name: "Database Design/Development",
      category: ["developer"],
      type: "proficiency",
      primary: false,
    },
    {
      name: "User Interface Design",
      category: ["developer"],
      type: "proficiency",
      primary: false,
    },
    {
      name: "User Experience Design",
      category: ["developer"],
      type: "proficiency",
      primary: false,
    },
    {
      name: "Graphic Design",
      category: ["artist"],
      type: "proficiency",
      primary: false,
    },
    {
      name: "3D Modeling",
      category: ["artist"],
      type: "proficiency",
      primary: false,
    },
    {
      name: "Digital Illustration",
      category: ["artist"],
      type: "proficiency",
      primary: false,
    },
    {
      name: "PC",
      category: ["developer"],
      type: "operating system",
      primary: false,
    },
    {
      name: "Windows 10",
      category: ["developer"],
      type: "operating system",
      primary: false,
    },
    {
      name: "Windows 11",
      category: ["developer"],
      type: "operating system",
      primary: false,
    },
    {
      name: "MacOS X+",
      category: ["developer"],
      type: "operating system",
      primary: false,
    },
    {
      name: "Linux",
      category: ["developer"],
      type: "operating system",
      primary: false,
    },
    { name: "CSS3", category: ["developer"], type: "language", primary: false },
    {
      name: "LESS CSS",
      category: ["developer"],
      type: "language",
      primary: false,
    },
    { name: "SASS", category: ["developer"], type: "language", primary: true },
    { name: "ES6", category: ["developer"], type: "language", primary: false },
    {
      name: "jQuery",
      category: ["developer"],
      type: "language",
      primary: false,
    },
    {
      name: "NPM",
      category: ["developer"],
      type: "proficiency",
      primary: true,
    },
  ],
};
