function debounce(fn, ms) {
  console.log("Running debounce");
  let timer;

  return () => {
    clearTimeout(timer);
    timer = setTimeout(() => {
      timer = null;
      fn.apply(this, arguments);
    }, ms);
  };
}

const states = new Map([
  ["Alabama", "AL"],
  ["Alaska", "AK"],
  ["Arizona", "AR"],
  ["Arkansas", "AZ"],
  ["American Samoa", "AS"],
  ["California", "CA"],
  ["Colorado", "CO"],
  ["Connecticut", "CT"],
  ["Delaware", "DE"],
  ["District of Columbia", "DC"],
  ["Florida", "FL"],
  ["Georgia", "GA"],
  ["Guam", "GU"],
  ["Hawaii", "HI"],
  ["Illinois", "IL"],
  ["Indiana", "IN"],
  ["Iowa", "IA"],
  ["Kansas", "KS"],
  ["Kentucky", "KY"],
  ["Louisiana", "LA"],
  ["Maine", "ME"],
  ["Maryland", "MD"],
  ["Massachusetts", "MA"],
  ["Michigan", "MI"],
  ["Minnesota", "MN"],
  ["Mississippi", "MS"],
  ["Missouri", "MO"],
  ["Montana", "MT"],
  ["Nebraska", "NE"],
  ["Nevada", "NV"],
  ["New Hampshire", "NH"],
  ["New Jersey", "NJ"],
  ["New Mexico", "NM"],
  ["New York", "NY"],
  ["North Carolina", "NC"],
  ["North Dakota", "ND"],
  ["Northern Mariana Islands", "CM"],
  ["Ohio", "OH"],
  ["Oklahoma", "OK"],
  ["Oregon", "OR"],
  ["Pennsylvania", "PA"],
  ["Puerto Rico", "PR"],
  ["Rhode Island", "RI"],
  ["South Carolina", "SC"],
  ["Tennessee", "TN"],
  ["Texas", "TX"],
  ["Trust Territories", "TT"],
  ["Utah", "UT"],
  ["Vermont", "VT"],
  ["Virginia", "VA"],
  ["Virgin Islands", "VI"],
  ["Washington", "WA"],
  ["West Virginia", "WV"],
  ["Wisconsin", "WI"],
  ["Wyoming", "WY"],
]);

const skills = [
  {
    name: "HTML",
    type: "computer language",
    subType: "markup",
    group: "",
    abbr: "html",
  },
  {
    name: "CSS",
    type: "computer language",
    subType: "style sheet",
    group: "",
    abbr: "css",
  },
  {
    name: "Javascript",
    type: "computer language",
    subType: "style sheet",
    group: "",
    abbr: "js",
  },
  {
    name: "Node.js",
    type: "runtime environment",
    subType: "",
    group: "Javascript",
    abbr: "",
  },
  {
    name: "Express",
    type: "framework",
    subType: "",
    group: "Node.js",
    abbr: "",
  },
  {
    name: "React",
    type: "library",
    subType: "",
    group: "Javascript",
    abbr: "",
  },
  {
    name: "C#",
    type: "computer language",
    subType: "programming",
    abbr: "",
  },
  {
    name: "MongoDB",
    type: "database program",
    subType: "programming",
    group: "NoSQL",
    abbr: "",
  },
];

const iconMap = new Map([
  ["HTML", "H"],
  ["CSS", "C"],
  ["Javascript", "j"],
  ["Node.js", "D"],
  ["Express.js", ""],
  ["React", "R"],
  ["C#", "Y"],
  ["MongoDB", "M"],
  ["NoSQL", ""],
  ["MySQL", "F"],
  ["SQL", ""],
  ["MongoDB Compass", "M"],
  ["MongoDB Atlas", "M"],
  ["Mongoose", ""],
  ["Mongo Shell", "M"],
  ["MySQL Workbench", "F"],
  ["Postman", "I"],
  ["Git", "g"],
  ["GitHub", "K"],
  ["Squarespace", "s"],
  ["Adobe Creative Cloud", "u"],
  ["Adobe Photoshop", "-"],
  ["Adobe Illustrator", "="],
  ["Adobe InDesign", "_"],
  ["Adobe Acrobat", ""],
  ["Adobe Bridge", ""],
  ["Adobe XD", "+"],
  ["Figma", "e"],
  ["Microsoft Word", ""],
  ["Microsoft Excel", ""],
  ["PowerPoint", ""],
  ["Microsoft Outlook", ""],
  ["Microsoft Teams", ""],
  ["Visual Studio Code", ""],
  ["Autodesk Maya", ""],
  ["ZBrush", "Z"],
  ["Adobe Substance Painter", ""],
  ["Version Control", "g"],
  ["PC", "y"],
  ["Windows", "y"],
  ["Windows 10", "y"],
  ["Windows 11", "y"],
  ["MacOS", "a"],
  ["MacOS X+", "a"],
  ["Linux", "<"],
  ["CSS3", "C"],
  ["LESS", "L"],
  ["SASS", "E"],
  ["ES6", "J"],
  ["jQuery", "q"],
  ["NPM", "N"],
]);

export { states, skills, debounce, iconMap };
